import { StyleSheet } from 'react-native';

export const BG = '#000000ff';
export const CARD = '#0B1020';
export const ACCENT = '#4F46E5';
export const FG = '#F9FAFB';
export const MUTED = '#9CA3AF';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: BG,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.5)',
    marginRight: 8,
    marginBottom: 8,
  },
  chipActive: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  chipText: {
    fontSize: 13,
    color: '#e5e7eb',
  },
  chipTextActive: {
    color: '#0b1120',
  },
  headerTitle: {
    color: FG,
    fontSize: 24,
    fontWeight: '700',
  },
  requiredAsterisk: {
    color: '#f97373',
    fontWeight: '700',
  },
  inputErrorText: {
    color: '#f97373',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 4,
  },
  smallLabel: {
    color: MUTED,
    fontSize: 13,
  },
  streakPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111827',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  streakEmoji: {
    fontSize: 16,
    marginRight: 4,
  },
  streakText: {
    color: FG,
    fontSize: 13,
  },
  avatarPill: {
  marginLeft: 8,
  width: 42,          
  height: 42,        
  borderRadius: 24,   
  backgroundColor: '#111827',
  alignItems: 'center',
  justifyContent: 'center',
  overflow: 'hidden',
},
avatarEmoji: {
  fontSize: 28,     
},
avatarImage: {
  width: 42,        
  height: 42,
  borderRadius: 24,
},

  heroCard: {
    marginHorizontal: 16,
    marginTop: 16,
  },
  card: {
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
  },
  heroTitle: {
    color: FG,
    fontSize: 20,
    fontWeight: '700',
  },
  heroSubtitle: {
    color: MUTED,
    fontSize: 13,
    marginTop: 4,
  },
  heroStatsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  heroStatTouchable: {
    flex: 1,
  },
  heroStatLabel: {
    color: MUTED,
    fontSize: 12,
  },
  heroStatValue: {
    color: FG,
    fontSize: 18,
    fontWeight: '700',
  },
  heroStatHint: {
    color: MUTED,
    fontSize: 10,
    marginTop: 2,
  },
  heroAccuracyInlineMeter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
    marginTop: 10,
  },
  accuracyBarSegment: {
    width: 6,
    height: 18,
    borderRadius: 999,
    marginHorizontal: 1,
    backgroundColor: '#111827',
  },
  primaryBtn: {
    backgroundColor: ACCENT,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 16,
  },
  primaryBtnSmall: {
    backgroundColor: ACCENT,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#E5E7EB',
    fontWeight: '600',
    fontSize: 15,
  },
  primaryBtnSmallDisabled: {
    backgroundColor: '#4B5563',
  },
  secondaryBtnSmall: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  secondaryBtnSmallText: {
    color: ACCENT,
    fontWeight: '600',
    fontSize: 14,
  },
  secondaryBtn: {
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: ACCENT,
  },
  secondaryBtnText: {
    color: ACCENT,
    fontWeight: '600',
    fontSize: 14,
  },
  section: {
    marginTop: 16,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    color: FG,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  menuTile: {
    width: '48%',
    backgroundColor: CARD,
    padding: 12,
    borderRadius: 16,
  },
  menuIcon: {
    fontSize: 20,
    marginBottom: 6,
  },
  menuTitle: {
    color: FG,
    fontWeight: '600',
    marginBottom: 2,
  },
  menuSubtitle: {
    color: MUTED,
    fontSize: 11,
  },
  onboardContainer: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 24,
  },
  appTitle: {
    color: FG,
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 8,
  },
  appSubtitle: {
    color: MUTED,
    fontSize: 14,
    marginBottom: 24,
  },
  label: {
    color: FG,
    fontSize: 14,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#020617',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: FG,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  helperText: {
    color: MUTED,
    fontSize: 12,
    marginTop: 8,
  },
  simpleHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#111827',
    gap: 10,
  },
  categoryIcon: {
    fontSize: 26,
  },
  categoryTitle: {
    color: FG,
    fontSize: 17,
    fontWeight: '600',
  },
  categorySubtitle: {
    color: MUTED,
    fontSize: 12,
    marginTop: 2,
  },
  examCard: {
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#111827',
  },
  examTitle: {
    color: FG,
    fontSize: 16,
    fontWeight: '600',
  },
  examDescription: {
    color: MUTED,
    fontSize: 12,
    marginTop: 4,
  },
  examMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  examDifficulty: {
    color: MUTED,
    fontSize: 12,
  },
  examStart: {
    color: ACCENT,
    fontSize: 14,
    fontWeight: '600',
  },
  testHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    alignItems: 'flex-start',
  },
  questionTopic: {
    color: ACCENT,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  questionText: {
    color: FG,
    fontSize: 16,
    fontWeight: '500',
  },
  optionBtn: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1F2937',
    marginBottom: 8,
    backgroundColor: '#020617',
  },
  optionBtnSelected: {
    borderColor: ACCENT,
    backgroundColor: '#111827',
  },
  optionText: {
    color: FG,
    fontSize: 14,
  },
  optionTextSelected: {
    color: '#E5E7EB',
    fontWeight: '600',
  },
  fillInput: {
    backgroundColor: '#020617',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: FG,
    borderWidth: 1,
    borderColor: '#1F2937',
    marginBottom: 8,
    marginTop: 8,
  },
  wordBankRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
    gap: 6,
  },
  wordBankChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  wordBankText: {
    color: FG,
    fontSize: 12,
  },
  testFooterRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 104,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fraiahBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111827',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  fraiahIcon: {
    width: 20,
    height: 20,
    marginRight: 6,
    borderRadius: 4,
  },
  fraiahText: {
    color: FG,
    fontSize: 13,
  },
  resultsCard: {
    alignItems: 'center',
    marginTop: 40,
  },
  resultsScore: {
    color: FG,
    fontSize: 40,
    fontWeight: '800',
  },
  resultsSub: {
    color: MUTED,
    fontSize: 14,
    marginTop: 4,
  },
  resultsVerdict: {
    color: FG,
    fontSize: 15,
    fontWeight: '600',
    marginTop: 16,
    textAlign: 'center',
  },
  examStatCard: {
    backgroundColor: CARD,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#111827',
  },
  leaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CARD,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#111827',
  },
  leaderRowYou: {
    borderColor: ACCENT,
    backgroundColor: '#111827',
  },
  leaderRank: {
    color: FG,
    fontWeight: '700',
    width: 24,
  },
  leaderName: {
    color: FG,
    flex: 1,
    fontSize: 14,
  },
  leaderXP: {
    color: MUTED,
    fontSize: 13,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalInner: {
    backgroundColor: CARD,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitle: {
    color: FG,
    fontSize: 16,
    fontWeight: '700',
  },
  modalClose: {
    color: MUTED,
    fontSize: 20,
  },
  modalBody: {
    flex: 1,
  },
  chatBubble: {
    padding: 10,
    borderRadius: 12,
    marginBottom: 8,
    maxWidth: '90%',
  },
  chatBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: ACCENT,
  },
  chatBubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: '#020617',
  },
  chatBubbleText: {
    color: FG,
    fontSize: 13,
  },
  modalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  modalInput: {
    flex: 1,
    backgroundColor: '#020617',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: FG,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#1F2937',
    fontSize: 13,
  },
  modalSendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSendText: {
    color: FG,
    fontWeight: '700',
  },
  globalChatRow: {
    marginBottom: 6,
  },
  globalChatName: {
    color: MUTED,
    fontSize: 11,
  },
  globalChatText: {
    color: FG,
    fontSize: 13,
  },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#020617',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: FG,
    borderWidth: 1,
    borderColor: '#1F2937',
    marginRight: 8,
    fontSize: 13,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginLeft: 318,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  backButtonText: {
    color: '#FACC15',
    fontSize: 16,
  },
  bottomNav: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 24,
    paddingVertical: 10,
    flexDirection: 'row',
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavLabel: {
    fontSize: 11,
    color: MUTED,
  },
  bottomNavLabelActive: {
    color: ACCENT,
    fontWeight: '600',
  },
  accountAvatarWrapper: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  accountAvatarEmoji: {
    fontSize: 40,
  },
  accountAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    resizeMode: 'cover',
  },
  accountAvatarUploadBadge: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  accountName: {
    color: FG,
    fontSize: 18,
    fontWeight: '700',
    marginTop: 4,
  },
  accountXP: {
    color: MUTED,
    fontSize: 13,
    marginTop: 4,
    marginBottom: 12,
  },
  rewardsCard: {
    width: '100%',
    marginTop: 16,
  },
  splashContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogoWrapper: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#020617',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 12,
  },
  splashLogo: {
    width: 110,
    height: 110,
  },
  splashText: {
    marginTop: 18,
    color: FG,
    fontSize: 20,
    fontWeight: '700',
  },
  splashSubText: {
    marginTop: 8,
    color: MUTED,
    fontSize: 13,
  },
  centerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoModalCard: {
    backgroundColor: CARD,
    borderRadius: 20,
    padding: 20,
    width: '80%',
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  infoModalTitle: {
    color: FG,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  infoModalValue: {
    color: FG,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  infoModalText: {
    color: MUTED,
    fontSize: 13,
    marginTop: 4,
  },
  accuracyMeterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    marginBottom: 6,
  },
  accuracyBarSegmentLarge: {
    width: 10,
    height: 22,
    borderRadius: 999,
    marginHorizontal: 2,
    backgroundColor: '#111827',
  },
  pieContainer: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  pieLabelWrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pieLabelTop: {
    color: FG,
    fontSize: 12,
    fontWeight: '600',
  },
  fraiahInlineContainer: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    backgroundColor: CARD,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1F2937',
  },
  fraiahInlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 4,
  },
  fraiahInlineTitle: {
    color: FG,
    fontSize: 14,
    fontWeight: '600',
  },
  fraiahInlineClose: {
    color: MUTED,
    fontSize: 18,
  },
  fraiahInlineMessages: {
    maxHeight: 150,
    marginTop: 4,
  },
  fraiahInlineInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingBottom: 4,
  },
  fraiahInlineInput: {
    flex: 1,
    backgroundColor: '#020617',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: FG,
    borderWidth: 1,
    borderColor: '#1F2937',
    marginRight: 8,
    fontSize: 13,
  },
  fraiahInlineSendBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fraiahInlineSendText: {
    color: FG,
    fontWeight: '700',
    fontSize: 13,
  },
  settingsCard: {
    width: '100%',
    marginTop: 16,
  },
  settingsRow: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: '#111827',
  },
  settingsRowLabel: {
    color: FG,
    fontSize: 14,
    fontWeight: '600',
  },
  settingsRowDescription: {
    color: MUTED,
    fontSize: 11,
    marginTop: 2,
  },

  // Exam screen nav + dropdown overlay (below tabs only)
  examNavTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.25)',
  },
  examNavTab: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 6,
  },
  examNavTabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9ca3af',
  },
  examNavTabTextActive: {
    color: '#facc15', // active tab label yellow
  },
  examNavTabUnderline: {
    marginTop: 4,
    height: 3,
    borderRadius: 999,
    width: '70%',
    backgroundColor: '#facc15', // yellow underline
  },
  examOverlayRoot: {
    position: 'absolute',
    left: 0,
    right: 0,
    // This offset is "just below the header + tabs" – tweak if you want
    top: 134,
    bottom: 72, // keep space for BottomNav
    justifyContent: 'flex-start',
  },
  examOverlayBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(15,23,42,0.78)', // dark dim below tabs
  },
  examOverlayPanel: {
    marginHorizontal: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#020617',
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },

  logoutBtn: {
    backgroundColor: '#B91C1C',
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 24,
  },
  logoutBtnText: {
    color: '#F9FAFB',
    fontWeight: '600',
    fontSize: 14,
  },
});